### ISSUE TITLE
Print Stack Trace to log when it had been passed

### ISSUE THREAD

**Issue by zs-dima** [PlugFox/l#13]
Could be nice to print Stack Trace to log when it had been passed to the l.e() or l.w()
For example if we passing Error and Stack Trace to the Sentry - we expect to see clear Error message without Stack Trace and Stack Trace as additional record.
And for the debug it could be nice to always see Stack Trace in the console if it is possible.
Maybe it could be option to print Stack Trace.

**Comment by PlugFox** [comment]
@zs-dima @AErmek

![image](https://user-images.githubusercontent.com/7805176/216811448-dcad4496-9762-455d-bc76-351c841728fa.png)

**Comment by PlugFox** [comment]
@zs-dima @AErmek

https://pub.dev/packages/l/versions/3.3.0-dev
